### ISSUE TITLE
Tests not included in sdist tarball on pypi.org

### ISSUE THREAD

**Issue by dvzrv** [whwright/click-command-tree#5]
Hi! I'm about to package this project for Arch Linux.

Downstreams usually run tests, to ensure integration with the existing ecosystem (e.g. click, python interpreter in your case). The source tarballs (sdist) on pypi.org usually contain all needed files to build a given project and it's great if that also includes the tests :)

**Comment by whwright** [comment]
Hey thanks for the feedback! Sorry for the delay here.

This is one of the first projects I've put on pypi so the process is still a bit unknown to me. It looks like I just need to include the test file using a `MANIFEST.in` and then `python setup.py test` works. Is that correct?

**Comment by dvzrv** [comment]
> It looks like I just need to include the test file using a MANIFEST.in and then python setup.py test works. Is that correct?

Yeah, if you're using setuptools, then MANIFEST.in is probably still the place to tweak this.
I'd abstain from running tests via setup.py (it's deprecated). Plain pytest will work much better :)

**Comment by dvzrv** [comment]
We have now switched to upstream provided source tarballs due to the inadequacies of building from sdist tarballs:
https://rfc.archlinux.page/0020-sources-for-python-packaging/
